### ISSUE TITLE
Typing Mistake!

### ISSUE THREAD

**Issue by Habibu-R-ahman** [francesco-scar/CTF-writeups#1]
```py
from PIL import Image, ImageChops

im1 = Image.open(r"secret.png")
im2 = Image.open(r"original.png")

diff = ImageChops.difference(im1, im2)


thresh = 8
fn = lambda x : 255 if x > thresh else 0
r = fiff.convert('L').point(fn, mode='1')
r.save('diff_b_w.png')

diff.save('diff.png')
```
Here I found a typing mistake
 `r = fiff.convert('L').point(fn, mode='1')`
Maybe it is actually look like this
 `r = diff.convert('L').point(fn, mode='1')`

Let me know if i'm wrong. Thanks!

**Comment by francesco-scar** [comment]
You are right, i will change it right now.
Thank you
